export const Types = {
  UserRepository: Symbol.for("UserRepository"),
  OperatorRepository: Symbol.for("OperatorRepository"),
  AdminRepository: Symbol.for("AdminRepository"),
  DestinationRepository:Symbol.for('DestinationRepository'),
  PackageCategoryRepository:Symbol.for('PackageCategoryRepository'),
  PackageRepository:Symbol.for('PackageRepository'),
  UserService: Symbol.for("UserService"),
  OperatorService: Symbol.for("OperatorService"),
  AdminService: Symbol.for("AdminService"),
  CommonAuthService: Symbol.for("CommonAuthService"),
  SecurityService: Symbol.for("SecurityService"),
  MailService: Symbol.for("MailService"),
  BcryptHashService: Symbol.for("BcryptHashService"),
  CryptoHashService: Symbol.for("CryptoHashService"),
  TokenService: Symbol.for("TokenService"),
  UserController: Symbol.for("UserController"),
  OperatorController: Symbol.for("OperatorController"),
  AdminController: Symbol.for("AdminController"),
  CommonAuthController: Symbol.for("CommonAuthController"),
  AuthMiddleware: Symbol.for("AuthMiddleware"),
};
