export const ROUTES = {
  USER: {
    REGISTER: "/register",
    VERIFY_OTP: "/verify-otp",
    RESEND_OTP: "/resend-otp",
    LOGIN: "/login",
    GOOGLE: "/google",
    FORGOT_PASSWORD: "/forgot-password",
    RESET_PASSWORD: "/reset-password/:token",
    LOGOUT: "/logout",
    UPDATE_IMAGE: "/update-profile-image",
    UPDATE: "/update/:id",
    DELETE: "/delete/:id",
    PACKAGE_CATEGORIES: "/package-categories",
    PACKAGES_HOME: "/packages/home",
    PACKAGES: "/packages",
    PACKAGE: "/package/:id",
    RESET_PASSWORD_AUTH: "/reset-password-authenticated",
    DESTINATIONS: "/destinations",
    PACKAGE_FILTER: "/packages/filter",
    ACTIVE_PACKAGE_CATEGORIES: "/active-package-categories",
    DESTINATIONS_BY_PACKAGE_CATEGORY:
      "/destinations/package-category/:category",
    PACKAGES_BY_CATEGORY: "/packages/category/:category",
    WISHLISTS: "/wishlists",
    CREATE_WISHLIST_GROUP: "/wishlist/create",
    UPDATE_WISHLIST_GROUP: "/wishlist/update/:groupId",
    DELETE_WISHLIST_GROUP: "/wishlist/delete/:groupId",
    WISHLIST_TOGGLE: "/wishlist/toggle",
    WISHLIST_ADD_NOTE: "/wishlist/add-note/:groupId",
    WISHLIST_UPDATE_NOTE: "/wishlist/update-note/:groupId/:noteId",
    WISHLIST_DELETE_NOTE: "/wishlist/delete-note/:groupId/:noteId",
    WISHLIST_SHARE_LINK: "/wishlist/share-link/:groupId",
    WISHLIST_SHARED: "/wishlist/shared/:shareToken",
    REVIEWS: "/reviews/:packageId",
    CREATE_REVIEW: "/review/create/:packageId",
    UPDATE_REVIEW: "/review/update/:reviewId/:packageId",
    DELETE_REVIEW: "/review/delete/:reviewId/:packageId",
    CREATE_BOOKING: "/booking",
    PAYMENT_VERIFY: "/booking/payment/verify",
    BOOKING_BY_ORDER_ID: "/booking/:orderId",
    MY_BOOKINGS: "/my-bookings",
    COUPONS: "/coupons",
    VALIDATE_COUPONS: "/coupons/validate",
    WALLET: "/wallet",
    WALLET_TOPUP: "/wallet/topup",
    VERIFY_WALLET_TOPUP: "/wallet/verify-topup",
    CANCEL_BOOKING: "/booking/cancel/:bookingId",
  },
  OPERATOR: {
    REGISTER: "/register",
    VERIFY_OTP: "/verify-otp",
    RESEND_OTP: "/resend-otp",
    LOGIN: "/login",

    FORGOT_PASSWORD: "/forgot-password",
    RESET_PASSWORD: "/reset-password/:token",
    LOGOUT: "/logout",
    UPDATE_IMAGE: "/update-profile-image",
    UPDATE: "/update/:id",

    CREATE_PACKAGE: "/create-package",
    DESTINATIONS: "/destinations",
    PACKAGE_CATEGORIES: "/package-categories",
    RESET_PASSWORD_AUTH: "/reset-password-authenticated",
    MY_PACKAGES_COUNT: "/my-packages-count",
    PACKAGE: "/package/:id",
    DELETE_PACKAGE: "/package/delete/:id",
    PACKAGES_UPDATE: "/packages/update/:id",
    PACKAGES: "/packages/:id",
    COUPONS: "/coupons",
    CREATE_COUPON: "/coupon/create",
    COUPON: "/coupon/:id",
    UPDATE_COUPON: "/coupon/update/:id",
    TOGGLE_COUPON_STATUS: "/coupon/:id/toggle-status",
    BOOKINGS: "/bookings",
    DASHBOARD_DATA: "/dashboard-data",
    BOOKING_DETAILS: "/booking-details/:bookingId",
    UPDATE_GUEST_ATTENDANCE: "/booking/guest-attendance/:bookingId",
    CANCEL_BOOKING: "/booking/cancel/:bookingId",
    RESCHEDULE_BOOKING: "/booking/reschedule/:bookingId",
    VERIFY_CANCELLATION: "/booking/verify-cancellation/:bookingId",
  },
  ADMIN: {
    LOGIN: "/login",
    LOGOUT: "/logout",
    UPDATE_IMAGE: "/update-profile-image",
    UPDATE: "/update/:id",

    OPS_VERIFICATION_REQS: "/operators/get-verification-requests",
    OPS_VERIFY: "/operators/verify-operator/:id",
    OPS_LIST: "/operators",
    OPS_BLOCK: "/operators/block/:id",
    OPS_DELETE: "/operators/delete/:id",
    OPS_SINGLE: "/operators/single-operator/:id",
    OPS_UPDATE: "/operators/update/:id",
    OPS_COUNT: "/operators/total-count",
    OPS_PENDING_COUNT: "/operators/pending-verification-count",

    USERS_LIST: "/users",
    USERS_BLOCK: "/users/block/:id",
    USERS_DELETE: "/users/delete/:id",
    USERS_SINGLE: "/users/single-user/:id",
    USERS_UPDATE: "/users/update/:id",
    USER_COUNT: "/users/total-count",
    SIGNUP_TODAY: "/users/signup-today",

    CREATE_CATEGORY: "/create-package-category",
    CREATE_DESTINATION: "/create-destination",

    PACKAGES_LIST: "/packages",
    PACKAGE: "/package/:id",
    PACKAGES_UPDATE: "/packages/update/:id",
    DELETE_PACKAGE: "/package/delete/:id",
    RESET_PASSWORD_AUTH: "/reset-password-authenticated",
    CANCELLATION_REQUESTS: "/booking/cancellation-requests",
    PROCESS_CANCELLATION: "/booking/process-cancellation/:bookingId",
  },
  COMMON: {
    REFRESH: "/refresh",
  },
  RAZORPAY_WEBHOOK: {
    PAYMENTS: "/payments/razorpay-webhook",
  },
  CHAT: {
    MY_CHATS: "/my_chats",
    ACCESS_CHAT: "/access_chat",
    CHAT_MESSAGES: "/chat_messages/:chatId",
    CLEAR_MESSAGES:'/clear-messages/:chatId'
  },
  NOTIFICATION: {
    CREATE: "/create",
    USER_NOTIFICATIONS: "/user-notifications",
    MARK_AS_READ: "/mark-as-read/:notificationId",
    MARK_ALL_AS_READ: "/mark-all-as-read",
    CLEAR_ALL: "/clear-all",
  },
} as const;
